#ifndef CONTROL_DEFINITIONS
#define CONTROL_DEFINITIONS

#define CONTROL_MOVE_CURSOR 0
#define CONTROL_MOVE_UNIT   1
#define CONTROL_CHOOSE_TECH 2
#define CONTROL_CHOOSE_UNIT 3
#define CONTROL_TEXTBOX     4

#endif
