#ifndef VIEW_DEFINITIONS
#define VIEW_DEFINITIONS



#define VIEW_REDRAW_MAP         0
#define VIEW_REDRAW_CELL        1

#define VIEW_MOVE_CURSOR_RIGHT  2
#define VIEW_MOVE_CURSOR_LEFT   3
#define VIEW_MOVE_CURSOR_TOP    4
#define VIEW_MOVE_CURSOR_BOTTOM 5

#define SIDEBAR_PLAYER_BLOCK    2
#define SIDEBAR_CELL_BLOCK      10



#endif
